use_frameworks!

platform :ios, '8.0'

target 'UBShareActivities_Example' do
  pod 'UBShareActivities', :path => '../'

  target 'UBShareActivities_Tests' do
    inherit! :search_paths

    
  end
end
